// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkchztcfbwnbukpqejix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrY2h6dGNmYnduYnVrcHFlaml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjg1NjksImV4cCI6MjA3MjMwNDU2OX0.NK-ZWen5oFH8qbq8KX9p8tdZipTik2udQsfozb4eKs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});